name: Deploy Designer to PaaS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to create a build from
        required: true
        default: main
      space:
        description: The space to deploy to
        required: true
        default: sandbox
      environment:
        description: The environment to deploy with
        required: false

env:
  REGISTRY: ghcr.io

jobs:
  
  deploy-designer:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_IMAGE: communitiesuk/digital-form-builder/designer
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set environment variables
        run: |
          echo "DOCKER_IMAGE_TAG=${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:$GITHUB_SHA" >> $GITHUB_ENV
          echo 

      - name: list environment
        run: |
          echo $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cloudfoundary
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: get cf environment variables
        run: |
          cf api ${{ secrets.CF_API }}
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          cf target -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.space }}
          echo `cf env FDS-Designer-Persistent | grep -e 'aws_access_key_id' -e 'aws_secret_access_key' -e 'bucket_name' | sed "s/\"//g" | sed "s/,//g" | sed "s/: /=/g"` >> $GITHUB_ENV
          echo "echoing ${{ env.aws_access_key_id }}"
          cf env FDS-Designer-Persistent | grep "aws_access_key_id"
          cf env FDS-Designer-Persistent | grep "aws_secret_access_key"
          cf env FDS-Designer-Persistent | grep "bucket_name"
      - name: Deploy to Gov.uk PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cf api ${{ secrets.CF_API }}
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          cf target -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.space }}
          CF_DOCKER_PASSWORD=${{ secrets.GHCR_PAT }} cf push FDS-Designer-Persistent -f ./manifest.yml \
          --var S3_BUCKET=${{ env.bucket_name }}
          --var AWS_ACCESS_KEY_ID=${{ env.aws_access_key_id }}
          --var AWS_SECRET_ACCESS_KEY=${{ env.aws_secret_access_key }}
